### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email" : "test231@na.com",
  "password" : "pasdfsdf",
  "test" : "test"
}

### Find Unique User with a given ID
GET http://localhost:3000/auth/2

### Find all users with a given Email
GET http://localhost:3000/auth?email=test@na.com

### Delete a user given id
DELETE http://localhost:3000/auth/3

### Update a user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "email" : "test@email.aaa"
}
